name: http_extension
description: .
version: 1.0.0
homepage: https://github.com/hsul4n/dart-extensions/packages/http_extension

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.12.1

dev_dependencies:
  test: ^1.5.1
