name: flutter_extension
description: .
version: 1.0.0
homepage: https://github.com/hsul4n/dart-extension

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.5.1
